export const doctors = [
  { name: 'Dr. Sarthak Tike', email: 'sarthak.t@example.com', bgColor: 'bg-yellow-100' },
  { name: 'Dr. Varun Desai', email: 'varun.d@example.com', bgColor: 'bg-blue-100' },
  { name: 'Dr. Ankita Jain', email: 'ankita.j@example.com', bgColor: 'bg-purple-100' },
];


export const appointments = [
  {
    doctorIndex: 0,
    patientName: 'Gaurav Sharma',
    type: 'Bridges',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    status: 'Finished',
  },
  {
    doctorIndex: 0,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '12:00 AM',
    endTime: '1:00 PM',
    status: 'Ongoing',
  },
  {
    doctorIndex: 0,
    patientName: 'Riya Kumar',
    type: 'Scaling',
    startTime: '3:00 PM',
    endTime: '4:00 PM',
    status: 'Registered',
  },
  {
    doctorIndex: 1,
    patientName: 'Riya Kumar',
    type: 'Scaling',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    status: 'Finished',
  },
  {
    doctorIndex: 1,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    status: 'Ongoing',
  },
  {
    doctorIndex: 1,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '5:00 PM',
    endTime: '6:00 PM',
    status: 'Registered',
  },
  {
    doctorIndex: 2,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '9:00 AM',
    endTime: '10:00 AM',
    status: 'Finished',
  },
  {
    doctorIndex: 2,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    status: 'Finished',
  },
  {
    doctorIndex: 2,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    status: 'Ongoing',
  },
  {
    doctorIndex: 2,
    patientName: 'Soham Jain',
    type: 'Bleaching',
    startTime: '4:00 PM',
    endTime: '5:00 PM',
    status: 'Registered',
  },
];

